# Generated by Django 6.0.4 on 2026-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
