# Generated by Django 6.0.4 on 2026-04-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
