# Generated by Django 6.0.4 on 2026-04-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subject',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
