# Generated by Django 6.0.4 on 2026-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
